# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a197cf8d1675dbd4546aa95b0f4849dc8e01e96b569a6c945793fd8684b065637e0428a0f9eeceb0ea146e64b721a5ecc843b9c19eeebf5743316b7d7075dba3

test:
  secret_key_base: c88915bbd45231bb006f9968faed4ae0749f1c46282452075ceccceb848d67c3bf5b053d3e41b8138fae0ef8068c36b8d507723ecef8b042b294d86c8b03e80e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
